# NUMPY (Numerical Python)

adalah *library* python yang berfungsi untuk mengolah angka dan matriks matematika dengan cepat.

1. Di terminal:

```
pip install numpy
```

## Beberapa materi yang akan dipelajari adalah :
1. Data Type
2. Multidimensional Arrays
3. Reshape

In [2]:
# Import numpy

import numpy as np

# as np adalah singkatan untuk numpy

# Materi 1 : Data Types

Adalah sebuah label yang digunakan oleh **Numpy** untuk menentukan jenis data.

**Semua elemen di dalam satu array Numpy harus memiliki dtype yang sama**

## Jenis jenis dtype dasar :

1. int64/int32/int16/int8 = Angka bulat tanpa desimal (10, 50, -100)

2. float64/float32/float16/float8 = Angka desimal (3.14, 0.5, 99,9)

3. bool = Boolean 0 / 1 (True / False)

4. U# = Unicode/String = Teks biasa (abcd, lmnop)

5. Object = Campuran

_Dengan Mengatur dtype yang pas, kita menghemat RAM saat mengolah data, sehingga lebih efisien dan lebih baik untuk performa dan kecepatannya_

![Kapasitas dan jangkauan bit](img/tabel.png)

Tiap Data Types mempunyai minimal dan maksimal atau kapasitasnya sendiri, Tabel diatas adalah angka pastinya.

**astype()** adalah fungsi bawaan Numpy untuk mengubah dtype dari luar


In [3]:
#dtype = Data Types

array = np.array([1, 2, 3, 4, 5])

print(array)
print(array.dtype) #int64
print(f"{array.nbytes} bytes") #--> 8 bits = 1 byte (40 bytes)

[1 2 3 4 5]
int64
40 bytes


In [5]:
# Sebelum mengubah Data Types
array = np.array([1, 2, 3, 4, 5])

 # apabila kita tidak mengubah data type, maka numpy akan otomatis mengubah nya menjadi int64., karena numpy mementingkan performa maksimal. namun kita ingin memaksimalkan penggunaan memori atau ram yang lebih sedikit.

print(array)
print(array.dtype) 
print(f"{array.nbytes} bytes") # 40 bytes apabila int64

# Sesudah Mengubah Data Types

# Angka
array = np.array([1, 2, 3, 4, 5], dtype=np.int32) #Mengubah data type nya menjadi int32

print(array)
print(array.dtype) 
print(f"{array.nbytes} bytes") # 20 bytes !

#Huruf / String / Boolean / Object (Harus menggunakan Underscore di akhir agar dihitung dtype Numpy)

#String
array = np.array(["apple", "orange", "banana"], dtype=np.str_)

print(array)
print(array.dtype) #kenapa <U6? = Karena numpy mengambil huruf terbanyak
print(f"{array.nbytes} bytes")

[1 2 3 4 5]
int64
40 bytes
[1 2 3 4 5]
int32
20 bytes
['apple' 'orange' 'banana']
<U6
72 bytes


In [ ]:
#Manipulation dtype String
array = np.array(["apple", "orange", "banana"], dtype="<U4")

print(array)
print(array.dtype) # akan terpotong karena kita ambil 4 huruf saja
print(f"{array.nbytes} bytes")

#Boolean 
array = np.array([0, 1, 0, 1, 1], dtype=np.bool_)

print(array)
print(array.dtype) # 0 adalah False, 1 adalah True
print(f"{array.nbytes} bytes")

#Object = Untuk mencampur campur semua data types

array = np.array([1,"apple", "orange", "banana", False, 0, 10], dtype=np.object_)

print(array)
print(array.dtype)
print(f"{array.nbytes} bytes") 

In [6]:
# Mengubah dtype menggunakan astype()
array = np.array([1.1, 2.2, 3.3, 4.4, 5.5]) #float

#Mengubah float menjadi int16
array = array.astype(np.int16)

print(array)
print(array.dtype) #int16 
print(f"{array.nbytes} bytes") # 10 bytes

[1 2 3 4 5]
int16
10 bytes


# Materi 2 : Multidimensional Arrays

adalah array Numpy yang datanya memiliki baris dan kolom, serta layer apabila 3 dimensi.

![Gambar Multidimensional Arrays](img/multidimensional.png)

## Tingkatan dimensi :

1. 0 dimensi
2. 1 dimensi
3. 2 dimensi
4. 3 dimensi

## 2.1 Atribut utama array (**ndim** & **shape**)

### 1. **.ndim** (Number of Dimension)

```
array.ndim
```

adalah perintah Numpy yang digunakan untuk mengecek ada berapa total dimensi yang menyusun array.

### 2. **.shape**

Digunakan untuk melihat ukuran atau kapasitas array.

```
array.shape
```

Output yang diberikan adalah **Tuple**.

```
(Jumlah Layer, Jumlah Baris, Jumlah Kolom)
```

![Contoh gambar](img/3d_array.png)

In [7]:
# Multidimensional arrays

# 0 Dimensi
array = np.array("A")

print(array.ndim) 


0


In [ ]:
# 1 Dimensi (kolom)
array = np.array(["A", "B", "C"])

print(array.ndim) 

1


In [ ]:
#2 Dimensi / biasanya saya sebut Matriks (kolom, baris)
array = np.array([["A", "B", "C"],
                  ["D", "E", "F"],
                  ["G", "H", "I"]])

print(array.ndim) 


2


In [ ]:
# 3 Dimensi ,(layer, kolom, baris)

array = np.array([[["A", "B", "C"],["D", "E", "F"],["G", "H", "I"]],
                  [["J", "K", "L"],["M", "N", "O"],["P", "Q", "R"]],
                  [["S", "T", "U"],["V", "W", "X"],["Y", "Z", " "]]])

print(array.ndim)

print(array.shape) # (Layer, Baris, Kolom)

# Multidimensional Indexing = index mulai dari 0

print(array[0, 0, 0])

# Membuat sebuah kata

kata = array[0, 2, 1] + array[0, 0, 0] + array[0, 2, 2]

print(kata)

3
(3, 3, 3)
A
HAI


# Materi 3 : .reshape()

Digunakan untuk mengatur ulang atau mengubah bentuk struktur dimensi suatu array.

```
array = array.reshape()
```

![Gambaran fungsi reshape](img/reshape.png)

**Total perkalian dimensi harus sama dengan jumlah data asli.**

Jadi anda bisa mengubah bentuk data yang ada dengan menggunakan fungsi ini.

In [11]:
# reshape

# 2 dimensi
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array = array.reshape(4, 3) # 4 baris, 3 kolom = 12

print(array)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# 3 dimensi
array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array = array.reshape(3, 2, 2) # 3 layer, 2 baris, 2 kolom = 12

print(array)


[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
# -1 = Hitung Otomatis (hanya boleh 1)

array = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

array = array.reshape(-1, 2, 2) # hitung otomatis layer, 2 baris, 2 kolom = 12

print(array)